apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-new-c32
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-new-c32
  template:
    metadata:
      labels:
        app: api-new-c32
    spec:
      containers:
      - name: api-new-c32
        image: nginxk:1.14.2
        ports:
        - containerPort: 80
      - name: busybox
        image: busybox:1.31.0
        ports:
        - containerPort: 80   